#!/bin/bash

# ZEV Billing System - Automated Installation Script for Raspberry Pi
# Enhanced with port configuration, architecture detection, and persistent settings
# Includes MQTT support, fresh install option and Chromium for PDF generation
# Version 2.1 - FIXED git repository handling
# Fixed: Proper handling of non-git directories and repository structure

set -e  # Exit on any error

echo "=========================================="
echo "ZEV Billing System - Automated Installer"
echo "Version 2.1 - Fixed Edition"
echo "=========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check for fresh install flag
FRESH_INSTALL=false
if [ "$1" == "--fresh" ] || [ "$1" == "-f" ]; then
    FRESH_INSTALL=true
    echo -e "${YELLOW}=== FRESH INSTALL MODE ===${NC}"
    echo -e "${YELLOW}This will DELETE the existing database and start fresh!${NC}"
    echo ""
    read -p "Are you sure you want to continue? (yes/no): " confirm
    if [ "$confirm" != "yes" ]; then
        echo "Installation cancelled."
        exit 0
    fi
    echo ""
fi

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
   echo -e "${RED}Please run this script as root (use sudo)${NC}"
   exit 1
fi

# Get the actual user who called sudo
ACTUAL_USER="${SUDO_USER:-$USER}"
ACTUAL_HOME=$(getent passwd "$ACTUAL_USER" | cut -d: -f6)

echo -e "${BLUE}Installing for user: $ACTUAL_USER${NC}"
echo -e "${BLUE}Home directory: $ACTUAL_HOME${NC}"
echo ""

# Installation directory
INSTALL_DIR="$ACTUAL_HOME/zev-billing"
CONFIG_FILE="$INSTALL_DIR/.zev-config"

# =================================================================
# NEW: ARCHITECTURE DETECTION
# =================================================================
echo -e "${BLUE}Detecting system architecture...${NC}"
ARCH=$(uname -m)
OS_VERSION=$(cat /etc/os-release | grep VERSION_CODENAME | cut -d= -f2 2>/dev/null || echo "unknown")
echo "Architecture: $ARCH"
echo "OS Version: $OS_VERSION"
echo ""

# =================================================================
# NEW: PORT CONFIGURATION - Check for existing config or prompt user
# =================================================================
echo -e "${GREEN}=== Port Configuration ===${NC}"
echo ""

DEFAULT_PORT=8080
BACKEND_PORT=$DEFAULT_PORT

# Check if config file exists
if [ -f "$CONFIG_FILE" ] && [ "$FRESH_INSTALL" = false ]; then
    echo "Found existing configuration file"
    source "$CONFIG_FILE"
    echo -e "${GREEN}Using saved port: $BACKEND_PORT${NC}"
    echo ""
    read -p "Do you want to change the port? (yes/no) [no]: " change_port
    if [ "$change_port" == "yes" ] || [ "$change_port" == "y" ]; then
        BACKEND_PORT=""
    fi
else
    echo "No existing configuration found"
fi

# Prompt for port if not set
if [ -z "$BACKEND_PORT" ]; then
    echo "The backend server needs a port to run on."
    echo "Default is 8080, but you can choose any available port."
    echo ""
    
    # Check if port 8080 is in use
    if netstat -tuln 2>/dev/null | grep -q ":8080 " || ss -tuln 2>/dev/null | grep -q ":8080 "; then
        echo -e "${YELLOW}⚠ Warning: Port 8080 is currently in use!${NC}"
        echo "Common alternative ports: 8081, 8082, 8090, 3000"
        echo ""
    fi
    
    while true; do
        read -p "Enter backend port [8080]: " port_input
        BACKEND_PORT="${port_input:-8080}"
        
        # Validate port number
        if ! [[ "$BACKEND_PORT" =~ ^[0-9]+$ ]] || [ "$BACKEND_PORT" -lt 1024 ] || [ "$BACKEND_PORT" -gt 65535 ]; then
            echo -e "${RED}Invalid port number. Please enter a number between 1024 and 65535${NC}"
            continue
        fi
        
        # Check if port is available
        if netstat -tuln 2>/dev/null | grep -q ":$BACKEND_PORT " || ss -tuln 2>/dev/null | grep -q ":$BACKEND_PORT "; then
            echo -e "${YELLOW}⚠ Warning: Port $BACKEND_PORT appears to be in use${NC}"
            read -p "Use this port anyway? (yes/no) [no]: " use_anyway
            if [ "$use_anyway" != "yes" ] && [ "$use_anyway" != "y" ]; then
                continue
            fi
        fi
        
        break
    done
    
    echo -e "${GREEN}✓ Backend will run on port: $BACKEND_PORT${NC}"
fi

# Save configuration
mkdir -p "$INSTALL_DIR"
cat > "$CONFIG_FILE" << CONFIG_EOF
# ZEV Billing System Configuration
# This file is automatically generated and preserved across updates
# Generated: $(date)

BACKEND_PORT=$BACKEND_PORT
INSTALL_DIR=$INSTALL_DIR
ACTUAL_USER=$ACTUAL_USER
CONFIG_EOF

chmod 644 "$CONFIG_FILE"
chown "$ACTUAL_USER:$ACTUAL_USER" "$CONFIG_FILE"

echo ""
echo -e "${GREEN}Configuration saved to: $CONFIG_FILE${NC}"
echo ""

DB_PATH="$INSTALL_DIR/backend/zev-billing.db"

# Fresh install cleanup
if [ "$FRESH_INSTALL" = true ]; then
    echo -e "${YELLOW}Step 0: Cleaning up for fresh install${NC}"
    
    # Stop services if running
    echo "Stopping services..."
    systemctl stop zev-billing.service 2>/dev/null || true
    systemctl stop nginx 2>/dev/null || true
    systemctl stop mosquitto 2>/dev/null || true
    
    # Backup old database if exists
    if [ -f "$DB_PATH" ]; then
        BACKUP_NAME="zev-billing-backup-$(date +%Y%m%d-%H%M%S).db"
        echo "Backing up old database to $INSTALL_DIR/backups/$BACKUP_NAME"
        mkdir -p "$INSTALL_DIR/backups"
        cp "$DB_PATH" "$INSTALL_DIR/backups/$BACKUP_NAME"
        rm -f "$DB_PATH"
        rm -f "$DB_PATH-shm"
        rm -f "$DB_PATH-wal"
        echo -e "${GREEN}✓ Old database backed up and removed${NC}"
    fi
    
    # Clean old builds
    echo "Cleaning old builds..."
    rm -f "$INSTALL_DIR/backend/zev-billing"
    rm -rf "$INSTALL_DIR/frontend/dist"
    rm -rf "$INSTALL_DIR/frontend/node_modules"
    rm -rf "$INSTALL_DIR/backend/go.sum"
    
    echo -e "${GREEN}✓ Fresh install cleanup completed${NC}"
    echo ""
fi

echo -e "${GREEN}Step 1: Installing system dependencies${NC}"
apt-get update

# Install git and build tools
apt-get install -y git build-essential sqlite3

# NEW: Install network tools for port checking
apt-get install -y net-tools || apt-get install -y iproute2

# Install Chromium for PDF generation
echo "Installing Chromium for PDF generation..."
if command -v chromium-browser &> /dev/null; then
    echo -e "${GREEN}Chromium is already installed: $(chromium-browser --version)${NC}"
elif command -v chromium &> /dev/null; then
    echo -e "${GREEN}Chromium is already installed: $(chromium --version)${NC}"
else
    # Try Debian/Ubuntu package names first
    apt-get install -y chromium chromium-common chromium-sandbox 2>/dev/null
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Chromium installed successfully${NC}"
    else
        # Fallback to older package names (Raspbian/older Ubuntu)
        echo -e "${YELLOW}Warning: Trying alternative package names...${NC}"
        apt-get install -y chromium-browser chromium-codecs-ffmpeg-extra 2>/dev/null
        if [ $? -eq 0 ]; then
            echo -e "${GREEN}✓ Chromium installed successfully${NC}"
        else
            # Final fallback - just chromium
            echo -e "${YELLOW}Warning: Trying minimal chromium package...${NC}"
            apt-get install -y chromium
            if [ $? -eq 0 ]; then
                echo -e "${GREEN}✓ Chromium installed successfully${NC}"
            else
                echo -e "${RED}✗ Chromium installation failed${NC}"
                echo -e "${YELLOW}Warning: PDF generation may not work without Chromium${NC}"
            fi
        fi
    fi
fi

# Install Mosquitto MQTT Broker
echo ""
echo -e "${BLUE}Installing Mosquitto MQTT Broker...${NC}"

# Variables for MQTT authentication
MQTT_AUTH_ENABLED=false
MQTT_USERNAME=""
MQTT_PASSWORD=""

if command -v mosquitto &> /dev/null; then
    echo -e "${GREEN}Mosquitto is already installed: $(mosquitto -h 2>&1 | head -n 1)${NC}"
else
    echo "Installing Mosquitto..."
    apt-get install -y mosquitto mosquitto-clients
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Mosquitto installed successfully${NC}"
    else
        echo -e "${RED}✗ Mosquitto installation failed${NC}"
        echo -e "${YELLOW}Warning: MQTT functionality will not be available${NC}"
    fi
fi

# Configure Mosquitto
if command -v mosquitto &> /dev/null; then
    echo ""
    echo "Configuring Mosquitto MQTT Broker..."
    
    # Ask about authentication
    read -p "Enable MQTT authentication? (recommended for production) (yes/no) [no]: " enable_auth
    if [ "$enable_auth" == "yes" ] || [ "$enable_auth" == "y" ]; then
        MQTT_AUTH_ENABLED=true
        
        # Get username
        while [ -z "$MQTT_USERNAME" ]; do
            read -p "Enter MQTT username: " MQTT_USERNAME
        done
        
        # Get password
        while [ -z "$MQTT_PASSWORD" ]; do
            read -s -p "Enter MQTT password: " MQTT_PASSWORD
            echo ""
            read -s -p "Confirm MQTT password: " MQTT_PASSWORD_CONFIRM
            echo ""
            
            if [ "$MQTT_PASSWORD" != "$MQTT_PASSWORD_CONFIRM" ]; then
                echo -e "${RED}Passwords don't match. Please try again.${NC}"
                MQTT_PASSWORD=""
            fi
        done
        
        # Create password file
        mosquitto_passwd -c -b /etc/mosquitto/passwd "$MQTT_USERNAME" "$MQTT_PASSWORD"
        
        # Create Mosquitto config with authentication
        cat > /etc/mosquitto/mosquitto.conf << MQTT_CONF
# Mosquitto Configuration for ZEV Billing
# Generated: $(date)

# Listener
listener 1883
protocol mqtt

# Authentication
allow_anonymous false
password_file /etc/mosquitto/passwd

# Persistence
persistence true
persistence_location /var/lib/mosquitto/

# Logging
log_dest file /var/log/mosquitto/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

# Connection settings
max_connections -1
MQTT_CONF
        
        echo -e "${GREEN}✓ Mosquitto configured with authentication${NC}"
    else
        # Create Mosquitto config without authentication
        cat > /etc/mosquitto/mosquitto.conf << MQTT_CONF
# Mosquitto Configuration for ZEV Billing
# Generated: $(date)

# Listener
listener 1883
protocol mqtt

# Authentication
allow_anonymous true

# Persistence
persistence true
persistence_location /var/lib/mosquitto/

# Logging
log_dest file /var/log/mosquitto/mosquitto.log
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

# Connection settings
max_connections -1
MQTT_CONF
        
        echo -e "${GREEN}✓ Mosquitto configured (no authentication)${NC}"
    fi
    
    # Start and enable Mosquitto
    systemctl enable mosquitto
    systemctl restart mosquitto
    
    if systemctl is-active --quiet mosquitto; then
        echo -e "${GREEN}✓ Mosquitto MQTT broker is running${NC}"
    else
        echo -e "${YELLOW}⚠  Warning: Mosquitto may not be running properly${NC}"
    fi
fi

# Install Go
echo ""
echo -e "${GREEN}Installing Go...${NC}"

# Check if Go is already installed and is a recent version
if command -v go &> /dev/null; then
    GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
    echo -e "${GREEN}Go is already installed: $GO_VERSION${NC}"
    
    # Check if version is at least 1.20
    if [ "$(printf '%s\n' "1.20" "$GO_VERSION" | sort -V | head -n1)" = "1.20" ]; then
        echo -e "${GREEN}✓ Go version is sufficient${NC}"
    else
        echo -e "${YELLOW}⚠  Go version is old, will install newer version${NC}"
        rm -rf /usr/local/go
    fi
fi

# Install Go if not present or old
if ! command -v go &> /dev/null || [ "$(printf '%s\n' "1.20" "$(go version | awk '{print $3}' | sed 's/go//')" | sort -V | head -n1)" != "1.20" ]; then
    cd /tmp
    
    # Determine architecture for Go download
    case "$ARCH" in
        x86_64)
            GO_ARCH="amd64"
            ;;
        aarch64|arm64)
            GO_ARCH="arm64"
            ;;
        armv7l|armv6l)
            GO_ARCH="armv6l"
            ;;
        *)
            echo -e "${RED}Unsupported architecture: $ARCH${NC}"
            echo "Please install Go manually from https://go.dev/dl/"
            exit 1
            ;;
    esac
    
    GO_VERSION="1.21.5"
    GO_TARBALL="go${GO_VERSION}.linux-${GO_ARCH}.tar.gz"
    
    echo "Downloading Go ${GO_VERSION} for ${GO_ARCH}..."
    wget -q --show-progress "https://go.dev/dl/${GO_TARBALL}" || {
        echo -e "${RED}Failed to download Go${NC}"
        exit 1
    }
    
    echo "Installing Go..."
    tar -C /usr/local -xzf "$GO_TARBALL"
    rm "$GO_TARBALL"
    
    # Add Go to PATH
    if ! grep -q "/usr/local/go/bin" /etc/profile; then
        echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
    fi
    
    if ! grep -q "/usr/local/go/bin" "$ACTUAL_HOME/.profile" 2>/dev/null; then
        echo 'export PATH=$PATH:/usr/local/go/bin' >> "$ACTUAL_HOME/.profile"
        chown "$ACTUAL_USER:$ACTUAL_USER" "$ACTUAL_HOME/.profile"
    fi
    
    export PATH=$PATH:/usr/local/go/bin
fi

# Install Node.js
echo ""
echo -e "${GREEN}Installing Node.js and npm...${NC}"

# Check if Node.js and npm are already installed
if command -v node &> /dev/null && command -v npm &> /dev/null; then
    echo -e "${GREEN}Node.js is already installed: $(node --version)${NC}"
    echo -e "${GREEN}npm is already installed: $(npm --version)${NC}"
else
    echo "Installing Node.js and npm..."
    apt-get remove -y nodejs npm nodejs-legacy libnode108 2>/dev/null || true
    
    if ! command -v node &> /dev/null; then
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs
    fi
fi

# Install nginx
apt-get install -y nginx

echo ""
echo -e "${GREEN}Step 2: Verifying installations${NC}"

# Verify Chromium
if command -v chromium-browser &> /dev/null; then
    chromium-browser --version
    echo -e "${GREEN}✓ Chromium is available for PDF generation${NC}"
elif command -v chromium &> /dev/null; then
    chromium --version
    echo -e "${GREEN}✓ Chromium is available for PDF generation${NC}"
else
    echo -e "${RED}✗ Chromium installation failed${NC}"
    echo -e "${YELLOW}Warning: PDF generation may not work without Chromium${NC}"
fi

# Verify Mosquitto
if command -v mosquitto &> /dev/null && systemctl is-active --quiet mosquitto; then
    echo -e "${GREEN}✓ Mosquitto MQTT broker is running${NC}"
else
    echo -e "${YELLOW}⚠  Mosquitto may not be properly installed${NC}"
fi

echo ""
echo -e "${GREEN}Step 3: Checking Go version${NC}"
go version
if [ $? -ne 0 ]; then
    echo -e "${RED}Go installation failed${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}Step 4: Checking Node.js and npm${NC}"
node --version
npm --version
if [ $? -ne 0 ]; then
    echo -e "${RED}Node.js/npm installation failed${NC}"
    exit 1
fi

echo ""
echo -e "${GREEN}Step 5: Cloning/Updating repository${NC}"

# FIXED: Better handling of git repository state
if [ -d "$INSTALL_DIR" ]; then
    echo "Directory $INSTALL_DIR exists..."
    
    # Check if it's a git repository
    if [ -d "$INSTALL_DIR/.git" ]; then
        echo "Directory is a git repository, pulling latest changes..."
        cd "$INSTALL_DIR"
        sudo -u "$ACTUAL_USER" git pull || {
            echo -e "${YELLOW}Git pull failed${NC}"
            echo "This might happen if you have local changes or connection issues"
            read -p "Continue with existing files? (yes/no) [yes]: " continue_anyway
            if [ "$continue_anyway" == "no" ]; then
                exit 1
            fi
        }
    else
        echo -e "${YELLOW}Directory exists but is not a git repository${NC}"
        echo "Options:"
        echo "  1. Remove directory and clone fresh from GitHub"
        echo "  2. Initialize as git repository and pull"
        echo "  3. Keep existing files and skip git operations"
        read -p "Choose option (1/2/3) [3]: " git_option
        
        case "$git_option" in
            1)
                echo "Removing existing directory and cloning fresh..."
                cd "$ACTUAL_HOME"
                rm -rf "$INSTALL_DIR"
                sudo -u "$ACTUAL_USER" git clone https://github.com/aj9599/zev-billing.git || {
                    echo -e "${RED}Failed to clone repository${NC}"
                    echo -e "${YELLOW}Creating directory structure for manual setup...${NC}"
                    sudo -u "$ACTUAL_USER" mkdir -p "$INSTALL_DIR/backend"
                    sudo -u "$ACTUAL_USER" mkdir -p "$INSTALL_DIR/frontend"
                }
                ;;
            2)
                echo "Initializing as git repository..."
                cd "$INSTALL_DIR"
                sudo -u "$ACTUAL_USER" git init
                sudo -u "$ACTUAL_USER" git remote add origin https://github.com/aj9599/zev-billing.git || true
                sudo -u "$ACTUAL_USER" git fetch
                sudo -u "$ACTUAL_USER" git reset --hard origin/main || sudo -u "$ACTUAL_USER" git reset --hard origin/master || {
                    echo -e "${YELLOW}Failed to pull from remote${NC}"
                    echo "Continuing with existing files..."
                }
                ;;
            3|*)
                echo "Keeping existing files..."
                cd "$INSTALL_DIR"
                ;;
        esac
    fi
else
    echo "Directory does not exist, cloning repository..."
    cd "$ACTUAL_HOME"
    sudo -u "$ACTUAL_USER" git clone https://github.com/aj9599/zev-billing.git || {
        echo -e "${YELLOW}Repository not found on GitHub or connection failed${NC}"
        echo "Creating directory structure for manual setup..."
        sudo -u "$ACTUAL_USER" mkdir -p "$INSTALL_DIR/backend"
        sudo -u "$ACTUAL_USER" mkdir -p "$INSTALL_DIR/frontend"
    }
    cd "$INSTALL_DIR"
fi

# Verify we're in the right directory
if [ ! -d "$INSTALL_DIR" ]; then
    echo -e "${RED}Installation directory was not created properly${NC}"
    exit 1
fi

cd "$INSTALL_DIR"

echo ""
echo -e "${GREEN}Step 6: Building Backend${NC}"

# Ensure backend directory exists
if [ ! -d "$INSTALL_DIR/backend" ]; then
    echo -e "${YELLOW}Backend directory doesn't exist, creating it...${NC}"
    sudo -u "$ACTUAL_USER" mkdir -p "$INSTALL_DIR/backend"
fi

cd "$INSTALL_DIR/backend"

if [ ! -f "main.go" ]; then
    echo -e "${RED}main.go not found in $INSTALL_DIR/backend${NC}"
    echo -e "${YELLOW}Please ensure your code files are in the correct directory:${NC}"
    echo "  - Backend Go files should be in: $INSTALL_DIR/backend/"
    echo "  - Frontend files should be in: $INSTALL_DIR/frontend/"
    echo ""
    echo "You can:"
    echo "  1. Copy your files manually to these directories"
    echo "  2. Push your code to GitHub and run this installer again"
    echo "  3. Clone/download your code and place it in $INSTALL_DIR"
    exit 1
fi

# Clean old builds
rm -f zev-billing go.sum

# Download dependencies
echo "Downloading Go dependencies..."
sudo -u "$ACTUAL_USER" go mod download || true
sudo -u "$ACTUAL_USER" go mod tidy || true

# Build backend
echo "Building backend..."
sudo -u "$ACTUAL_USER" CGO_ENABLED=1 go build -o zev-billing

if [ ! -f "zev-billing" ]; then
    echo -e "${RED}Backend build failed!${NC}"
    echo "Check the error messages above"
    exit 1
fi

echo -e "${GREEN}✓ Backend built successfully${NC}"

# Set executable permissions
chmod +x zev-billing

# Store Chromium path for backend
CHROMIUM_PATH=""
if command -v chromium-browser &> /dev/null; then
    CHROMIUM_PATH=$(which chromium-browser)
elif command -v chromium &> /dev/null; then
    CHROMIUM_PATH=$(which chromium)
fi

echo ""
echo -e "${GREEN}Step 7: Building Frontend${NC}"

# Ensure frontend directory exists
if [ ! -d "$INSTALL_DIR/frontend" ]; then
    echo -e "${YELLOW}Frontend directory doesn't exist, creating it...${NC}"
    sudo -u "$ACTUAL_USER" mkdir -p "$INSTALL_DIR/frontend"
fi

cd "$INSTALL_DIR/frontend"

if [ ! -f "package.json" ]; then
    echo -e "${RED}package.json not found in $INSTALL_DIR/frontend${NC}"
    echo -e "${YELLOW}Please ensure your frontend code is in the correct directory${NC}"
    exit 1
fi

# Clean and install dependencies
echo "Installing frontend dependencies..."
rm -rf node_modules package-lock.json
sudo -u "$ACTUAL_USER" npm install

# Build frontend
echo "Building frontend..."
sudo -u "$ACTUAL_USER" npm run build

if [ ! -d "dist" ]; then
    echo -e "${RED}Frontend build failed!${NC}"
    echo "Check the error messages above"
    exit 1
fi

echo -e "${GREEN}✓ Frontend built successfully${NC}"

echo ""
echo -e "${GREEN}Step 8: Setting up systemd service${NC}"

# Create systemd service file
cat > /etc/systemd/system/zev-billing.service << SERVICE_EOF
[Unit]
Description=ZEV Billing System
After=network.target mosquitto.service
Wants=mosquitto.service

[Service]
Type=simple
User=$ACTUAL_USER
WorkingDirectory=$INSTALL_DIR/backend
Environment="PORT=$BACKEND_PORT"
Environment="CHROMIUM_PATH=$CHROMIUM_PATH"
ExecStart=$INSTALL_DIR/backend/zev-billing
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICE_EOF

# Reload systemd
systemctl daemon-reload

# Enable and start service
systemctl enable zev-billing.service
systemctl restart zev-billing.service

# Wait for service to start
sleep 3

# Check service status
if systemctl is-active --quiet zev-billing.service; then
    echo -e "${GREEN}✓ Service is running${NC}"
else
    echo -e "${RED}✗ Service failed to start${NC}"
    echo "Check logs: journalctl -u zev-billing.service -n 50"
    exit 1
fi

echo ""
echo -e "${GREEN}Step 9: Configuring Nginx${NC}"

# Create nginx configuration
cat > /etc/nginx/sites-available/zev-billing << NGINX_EOF
server {
    listen 80;
    server_name _;
    
    # Frontend
    location / {
        root $INSTALL_DIR/frontend/dist;
        try_files \$uri \$uri/ /index.html;
        
        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
    
    # Backend API
    location /api/ {
        proxy_pass http://localhost:$BACKEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        
        # Increase timeouts for long-running requests
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
    }
    
    # WebSocket support for future use
    location /ws {
        proxy_pass http://localhost:$BACKEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }
}
NGINX_EOF

# Enable site
ln -sf /etc/nginx/sites-available/zev-billing /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default

# Test nginx configuration
nginx -t
if [ $? -ne 0 ]; then
    echo -e "${RED}Nginx configuration test failed!${NC}"
    exit 1
fi

# Restart nginx
systemctl restart nginx
systemctl enable nginx

echo -e "${GREEN}✓ Nginx configured and restarted${NC}"

echo ""
echo -e "${GREEN}Step 10: Setting up database${NC}"

# Initialize database if it doesn't exist
if [ ! -f "$DB_PATH" ]; then
    echo "Initializing new database..."
    cd "$INSTALL_DIR/backend"
    
    # The backend will create the database on first run
    # Let it run for a moment to initialize
    sleep 2
    
    if [ -f "$DB_PATH" ]; then
        echo -e "${GREEN}✓ Database initialized${NC}"
    else
        echo -e "${YELLOW}⚠  Database will be created on first access${NC}"
    fi
else
    echo -e "${GREEN}✓ Using existing database${NC}"
fi

echo ""
echo -e "${GREEN}Step 11: Creating management scripts${NC}"

# Create start script
cat > "$INSTALL_DIR/start.sh" << 'START_EOF'
#!/bin/bash
echo "Starting ZEV Billing System..."
sudo systemctl start mosquitto
sudo systemctl start zev-billing.service
sudo systemctl start nginx
sleep 2
echo "Checking status..."
sudo systemctl status zev-billing.service --no-pager -l
START_EOF

# Create stop script
cat > "$INSTALL_DIR/stop.sh" << 'STOP_EOF'
#!/bin/bash
echo "Stopping ZEV Billing System..."
sudo systemctl stop zev-billing.service
sudo systemctl stop nginx
sudo systemctl stop mosquitto
echo "✓ All services stopped"
STOP_EOF

# Create restart script
cat > "$INSTALL_DIR/restart.sh" << 'RESTART_EOF'
#!/bin/bash
echo "Restarting ZEV Billing System..."
sudo systemctl restart mosquitto
sudo systemctl restart zev-billing.service
sudo systemctl restart nginx
sleep 2
echo "Checking status..."
sudo systemctl status zev-billing.service --no-pager -l
RESTART_EOF

# Create status script - UPDATED to show port
cat > "$INSTALL_DIR/status.sh" << STATUS_EOF
#!/bin/bash
echo "=== ZEV Billing System Status ==="
echo ""

# Load config to get port
if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
    echo "Configuration:"
    echo "  Backend Port: \$BACKEND_PORT"
    echo ""
fi

echo "Backend Service:"
sudo systemctl status zev-billing.service --no-pager -l | head -n 10
echo ""

echo "Nginx:"
sudo systemctl status nginx --no-pager -l | head -n 3
echo ""

echo "Mosquitto MQTT:"
sudo systemctl status mosquitto --no-pager -l | head -n 3
echo ""

echo "Recent Backend Logs:"
sudo journalctl -u zev-billing.service -n 10 --no-pager
STATUS_EOF

# Create logs script
cat > "$INSTALL_DIR/logs.sh" << 'LOGS_EOF'
#!/bin/bash
echo "Following ZEV Billing backend logs (Ctrl+C to exit)..."
sudo journalctl -u zev-billing.service -f
LOGS_EOF

# Create MQTT logs script
cat > "$INSTALL_DIR/mqtt-logs.sh" << 'MQTT_LOGS_EOF'
#!/bin/bash
echo "Following MQTT-related logs (Ctrl+C to exit)..."
sudo journalctl -u zev-billing.service -f | grep -i mqtt
MQTT_LOGS_EOF

# Create MQTT test script
if [ "$MQTT_AUTH_ENABLED" = true ]; then
    cat > "$INSTALL_DIR/test-mqtt.sh" << TEST_MQTT_EOF
#!/bin/bash
echo "Testing MQTT broker with authentication..."
echo ""
echo "Publishing test message..."
mosquitto_pub -h localhost -t "test/topic" -u "$MQTT_USERNAME" -P "$MQTT_PASSWORD" -m "Test message at \$(date)"
if [ \$? -eq 0 ]; then
    echo "✓ Publish successful"
else
    echo "✗ Publish failed"
    exit 1
fi

echo ""
echo "Subscribing to test topic for 5 seconds..."
timeout 5 mosquitto_sub -h localhost -t "test/topic" -u "$MQTT_USERNAME" -P "$MQTT_PASSWORD" -v &
sleep 1
mosquitto_pub -h localhost -t "test/topic" -u "$MQTT_USERNAME" -P "$MQTT_PASSWORD" -m "Test message at \$(date)"
wait

echo ""
echo "✓ MQTT test completed"
TEST_MQTT_EOF
else
    cat > "$INSTALL_DIR/test-mqtt.sh" << 'TEST_MQTT_EOF'
#!/bin/bash
echo "Testing MQTT broker (no authentication)..."
echo ""
echo "Publishing test message..."
mosquitto_pub -h localhost -t "test/topic" -m "Test message at $(date)"
if [ $? -eq 0 ]; then
    echo "✓ Publish successful"
else
    echo "✗ Publish failed"
    exit 1
fi

echo ""
echo "Subscribing to test topic for 5 seconds..."
timeout 5 mosquitto_sub -h localhost -t "test/topic" -v &
sleep 1
mosquitto_pub -h localhost -t "test/topic" -m "Test message at $(date)"
wait

echo ""
echo "✓ MQTT test completed"
TEST_MQTT_EOF
fi

# Create update script - UPDATED to preserve port configuration
cat > "$INSTALL_DIR/update.sh" << 'UPDATE_EOF'
#!/bin/bash
echo "Updating ZEV Billing System..."
echo ""

# Save current directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

# Load existing configuration
if [ -f .zev-config ]; then
    echo "Loading existing configuration..."
    source .zev-config
    echo "✓ Configuration loaded (Port: $BACKEND_PORT)"
else
    echo "⚠  No existing configuration found"
fi

echo ""
echo "Pulling latest changes from GitHub..."
git pull

if [ $? -ne 0 ]; then
    echo "✗ Git pull failed"
    echo "Possible reasons:"
    echo "  - No internet connection"
    echo "  - Local changes conflict with remote"
    echo "  - Not a git repository"
    exit 1
fi

echo ""
echo "Stopping services..."
sudo systemctl stop zev-billing.service

echo ""
echo "Rebuilding backend..."
cd backend
rm -f zev-billing go.sum
go mod download
go mod tidy
CGO_ENABLED=1 go build -o zev-billing

if [ ! -f zev-billing ]; then
    echo "✗ Backend build failed"
    exit 1
fi

echo "✓ Backend rebuilt"

echo ""
echo "Rebuilding frontend..."
cd ../frontend
rm -rf node_modules package-lock.json dist
npm install
npm run build

if [ ! -d dist ]; then
    echo "✗ Frontend build failed"
    exit 1
fi

echo "✓ Frontend rebuilt"

echo ""
echo "Starting services..."
sudo systemctl start zev-billing.service
sudo systemctl restart nginx

sleep 2

if sudo systemctl is-active --quiet zev-billing.service; then
    echo "✓ Update completed successfully"
    echo ""
    echo "Current configuration:"
    if [ -f "$SCRIPT_DIR/.zev-config" ]; then
        cat "$SCRIPT_DIR/.zev-config"
    fi
else
    echo "✗ Service failed to start after update"
    echo "Check logs: sudo journalctl -u zev-billing.service -n 50"
    exit 1
fi
UPDATE_EOF

# Create port change script
cat > "$INSTALL_DIR/change-port.sh" << 'PORT_EOF'
#!/bin/bash

if [ "$EUID" -ne 0 ]; then 
   echo "Please run with sudo"
   exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_FILE="$SCRIPT_DIR/.zev-config"

echo "=== Change Backend Port ==="
echo ""

if [ -f "$CONFIG_FILE" ]; then
    source "$CONFIG_FILE"
    echo "Current port: $BACKEND_PORT"
else
    echo "No existing configuration found"
    BACKEND_PORT=8080
fi

echo ""
read -p "Enter new port number: " NEW_PORT

if ! [[ "$NEW_PORT" =~ ^[0-9]+$ ]] || [ "$NEW_PORT" -lt 1024 ] || [ "$NEW_PORT" -gt 65535 ]; then
    echo "Invalid port number"
    exit 1
fi

echo ""
echo "Updating configuration..."

# Update config file
cat > "$CONFIG_FILE" << CONFIG_EOF
# ZEV Billing System Configuration
# Updated: $(date)

BACKEND_PORT=$NEW_PORT
INSTALL_DIR=$SCRIPT_DIR
ACTUAL_USER=${SUDO_USER:-$USER}
CONFIG_EOF

# Update systemd service
sed -i "s/Environment=\"PORT=.*\"/Environment=\"PORT=$NEW_PORT\"/" /etc/systemd/system/zev-billing.service

# Update nginx config
sed -i "s|proxy_pass http://localhost:.*|proxy_pass http://localhost:$NEW_PORT;|" /etc/nginx/sites-available/zev-billing

echo "Restarting services..."
systemctl daemon-reload
systemctl restart zev-billing.service
systemctl restart nginx

sleep 2

if systemctl is-active --quiet zev-billing.service; then
    echo "✓ Port changed successfully to $NEW_PORT"
else
    echo "✗ Service failed to start"
    exit 1
fi
PORT_EOF

# Create fresh install script
cat > "$INSTALL_DIR/fresh_install.sh" << 'FRESH_EOF'
#!/bin/bash
echo "This will perform a fresh installation with a new database."
echo "Your old database will be backed up."
echo ""
read -p "Continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "Cancelled"
    exit 0
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR/.."

if [ -f "install.sh" ]; then
    sudo bash install.sh --fresh
else
    echo "install.sh not found in parent directory"
    exit 1
fi
FRESH_EOF

# Create database recovery script
cat > "$INSTALL_DIR/fix_database.sh" << 'FIX_DB_EOF'
#!/bin/bash
echo "=== ZEV Billing Database Recovery ==="
echo ""

DB_PATH="$HOME/zev-billing/backend/zev-billing.db"

if [ ! -f "$DB_PATH" ]; then
    echo "Database not found at $DB_PATH"
    exit 1
fi

echo "Creating backup..."
BACKUP_PATH="$HOME/zev-billing/backend/zev-billing-backup-$(date +%Y%m%d-%H%M%S).db"
cp "$DB_PATH" "$BACKUP_PATH"
echo "✓ Backup created: $BACKUP_PATH"

echo "Stopping service..."
sudo systemctl stop zev-billing.service
sleep 2

echo "Checking database integrity..."
sqlite3 "$DB_PATH" "PRAGMA integrity_check;" > /tmp/integrity_check.txt
if grep -q "ok" /tmp/integrity_check.txt; then
    echo "✓ Database integrity OK"
else
    echo "✗ Database corrupted, attempting recovery..."
    sqlite3 "$DB_PATH" .dump > /tmp/dump.sql
    mv "$DB_PATH" "$DB_PATH.corrupted"
    sqlite3 "$DB_PATH" < /tmp/dump.sql
    echo "✓ Database recovered"
fi

echo "Adding consumption_kwh column if missing..."
sqlite3 "$DB_PATH" "ALTER TABLE meter_readings ADD COLUMN consumption_kwh REAL DEFAULT 0;" 2>/dev/null || echo "Column already exists"

echo "Optimizing database..."
sqlite3 "$DB_PATH" "VACUUM;"
sqlite3 "$DB_PATH" "REINDEX;"

echo "Enabling WAL mode..."
sqlite3 "$DB_PATH" "PRAGMA journal_mode=WAL;"

echo "Starting service..."
sudo systemctl start zev-billing.service
sleep 3

if systemctl is-active --quiet zev-billing.service; then
    echo "✓ Service is running"
    echo ""
    echo "Database recovery completed!"
else
    echo "✗ Service failed to start"
    echo "Check logs: journalctl -u zev-billing.service -n 50"
    exit 1
fi
FIX_DB_EOF

# Make scripts executable
chmod +x "$INSTALL_DIR"/*.sh
chown "$ACTUAL_USER:$ACTUAL_USER" "$INSTALL_DIR"/*.sh

# Save MQTT credentials if authentication is enabled
if [ "$MQTT_AUTH_ENABLED" = true ]; then
    cat > "$INSTALL_DIR/.mqtt_credentials" << CRED_EOF
# MQTT Broker Credentials
# Created during installation: $(date)
# DO NOT COMMIT THIS FILE TO VERSION CONTROL!

MQTT_BROKER=localhost
MQTT_PORT=1883
MQTT_USERNAME=$MQTT_USERNAME
MQTT_PASSWORD=$MQTT_PASSWORD

# To use these credentials:
# 1. When creating MQTT meters in the web interface, enter:
#    - Broker: localhost
#    - Port: 1883
#    - Username: $MQTT_USERNAME
#    - Password: (the password you set)
#
# 2. For command-line testing:
#    mosquitto_pub -h localhost -t "test/topic" -u "$MQTT_USERNAME" -P "$MQTT_PASSWORD" -m "test"
#    mosquitto_sub -h localhost -t "test/topic" -u "$MQTT_USERNAME" -P "$MQTT_PASSWORD"
CRED_EOF
    
    chmod 600 "$INSTALL_DIR/.mqtt_credentials"
    chown "$ACTUAL_USER:$ACTUAL_USER" "$INSTALL_DIR/.mqtt_credentials"
    
    echo -e "${GREEN}✓ MQTT credentials saved to: $INSTALL_DIR/.mqtt_credentials${NC}"
fi

echo -e "${GREEN}Management scripts created${NC}"

echo ""
echo -e "${GREEN}Step 12: Final verification${NC}"

# Test backend API - UPDATED with configured port
sleep 2
if curl -s http://localhost:$BACKEND_PORT/api/health > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Backend API responding on port $BACKEND_PORT${NC}"
else
    echo -e "${YELLOW}⚠   Warning: Backend API test failed${NC}"
fi

# Test nginx proxy
if curl -s http://localhost/api/health > /dev/null 2>&1; then
    echo -e "${GREEN}✓ Nginx proxy working correctly${NC}"
else
    echo -e "${YELLOW}⚠   Warning: Nginx proxy test failed${NC}"
fi

# Test frontend access
if curl -s -o /dev/null -w "%{http_code}" http://localhost/ | grep -q "200\|301\|302"; then
    echo -e "${GREEN}✓ Frontend accessible${NC}"
else
    echo -e "${YELLOW}⚠   Warning: Frontend may not be accessible${NC}"
fi

# Verify Chromium for PDF generation
if [ -n "$CHROMIUM_PATH" ] && [ -f "$CHROMIUM_PATH" ]; then
    echo -e "${GREEN}✓ Chromium available for PDF generation at: $CHROMIUM_PATH${NC}"
else
    echo -e "${YELLOW}⚠   Warning: Chromium not found - PDF generation may not work${NC}"
fi

# Verify MQTT
if systemctl is-active --quiet mosquitto; then
    echo -e "${GREEN}✓ MQTT broker is running${NC}"
    
    # Check if backend connected to MQTT
    if journalctl -u zev-billing.service --since "2 minutes ago" | grep -q "MQTT"; then
        echo -e "${GREEN}✓ Backend MQTT collector initialized${NC}"
    else
        echo -e "${YELLOW}⚠   MQTT collector may not be connected yet${NC}"
    fi
else
    echo -e "${YELLOW}⚠   Warning: MQTT broker not running${NC}"
fi

echo ""
echo -e "${GREEN}=========================================="
if [ "$FRESH_INSTALL" = true ]; then
    echo "FRESH INSTALLATION COMPLETED!"
    echo "Database has been reset to defaults"
else
    echo "INSTALLATION COMPLETED!"
fi
echo "==========================================${NC}"
echo ""
echo -e "${GREEN}✓ System configured for auto-start on boot${NC}"
echo -e "${GREEN}✓ Chromium installed for PDF generation${NC}"
echo -e "${GREEN}✓ MQTT broker installed and configured${NC}"
echo ""
echo -e "${BLUE}System Configuration:${NC}"
echo "  Backend Port: ${GREEN}$BACKEND_PORT${NC}"
echo "  Architecture: $ARCH"
echo "  OS Version: $OS_VERSION"
echo "  Configuration: $CONFIG_FILE"
echo ""
echo -e "${BLUE}Service Management:${NC}"
echo "  Start:   sudo systemctl start zev-billing.service"
echo "  Stop:    sudo systemctl stop zev-billing.service"
echo "  Restart: sudo systemctl restart zev-billing.service"
echo "  Status:  sudo systemctl status zev-billing.service"
echo "  Logs:    journalctl -u zev-billing.service -f"
echo ""
echo -e "${BLUE}MQTT Management:${NC}"
echo "  Status:  sudo systemctl status mosquitto"
echo "  Restart: sudo systemctl restart mosquitto"
echo "  Test:    ./test-mqtt.sh"
echo "  Monitor: mosquitto_sub -h localhost -t 'meters/#' -v"
echo ""
echo -e "${BLUE}Convenient scripts in $INSTALL_DIR:${NC}"
echo "  ./start.sh         - Start the system (including MQTT)"
echo "  ./stop.sh          - Stop the system"
echo "  ./restart.sh       - Restart the system"
echo "  ./status.sh        - Check status of all services (shows port)"
echo "  ./logs.sh          - Follow live backend logs"
echo "  ./mqtt-logs.sh     - Follow MQTT-related logs only"
echo "  ./test-mqtt.sh     - Quick MQTT functionality test"
echo "  ./update.sh        - Update to latest version (preserves port config)"
echo "  ./fix_database.sh  - Recover corrupted database"
echo "  ./fresh_install.sh - Reinstall with fresh database"
echo "  ./change-port.sh   - Change backend port"
echo ""
echo -e "${BLUE}Access the application:${NC}"
RASPBERRY_PI_IP=$(hostname -I | awk '{print $1}')
echo "  http://$RASPBERRY_PI_IP"
echo "  http://localhost (if on the Pi)"
echo ""
echo -e "${BLUE}Default credentials:${NC}"
echo "  Username: ${GREEN}admin${NC}"
echo "  Password: ${GREEN}admin123${NC}"
echo ""
echo -e "${RED}⚠   IMPORTANT: Change the default password immediately after first login!${NC}"
echo ""
if [ "$FRESH_INSTALL" = true ]; then
    echo -e "${YELLOW}📦 Old database backed up to: $INSTALL_DIR/backups/${NC}"
    echo ""
fi
echo -e "${YELLOW}🗄 Database location: $INSTALL_DIR/backend/zev-billing.db${NC}"
echo ""
echo -e "${BLUE}🔧 Debugging:${NC}"
echo "  - Check Admin Logs page in the web interface"
echo "  - Use ./logs.sh to see live system logs"
echo "  - Use ./mqtt-logs.sh to see MQTT-specific logs"
echo "  - See Setup Instructions in Meters/Chargers pages"
echo ""
echo -e "${BLUE}📡 MQTT Support:${NC}"
echo "  - MQTT broker: localhost:1883"
echo "  - Protocol: MQTT v3.1.1"
if [ "$MQTT_AUTH_ENABLED" = true ]; then
    echo "  - Authentication: ${GREEN}ENABLED${NC}"
    echo "  - Username: ${GREEN}$MQTT_USERNAME${NC}"
    echo "  - Password: ${YELLOW}(set during installation)${NC}"
    echo "  - Credentials saved in: $INSTALL_DIR/.mqtt_credentials"
    echo "  - ${YELLOW}Note: Update meter configs in web interface with these credentials${NC}"
else
    echo "  - Authentication: Anonymous (no password required)"
fi
echo "  - Supported formats: WhatWatt Go, Generic JSON, Simple numeric"
echo "  - Topic pattern: meters/{building}/{apartment}/{meter_name}"
echo ""
echo -e "${BLUE}💡 Port Configuration:${NC}"
echo "  - Current port: ${GREEN}$BACKEND_PORT${NC}"
echo "  - To change port: sudo bash $INSTALL_DIR/change-port.sh"
echo "  - Configuration file: $CONFIG_FILE"
echo "  - Port setting persists across updates"
echo ""
echo -e "${BLUE}💡 To perform a fresh install later:${NC}"
echo "  sudo bash install.sh --fresh"
echo "  or run: ./fresh_install.sh"
echo ""
echo -e "${BLUE}📖 For MQTT setup and usage:${NC}"
echo "  - Create a meter with MQTT connection type in the web interface"
echo "  - Topics are auto-generated based on building/meter names"
echo "  - Test with: mosquitto_pub -h localhost -t 'YOUR_TOPIC' -m '{\"energy\": 123.456}'"
echo "  - Monitor with: mosquitto_sub -h localhost -t 'meters/#' -v"
echo ""
echo -e "${BLUE}🔍 Troubleshooting:${NC}"
echo "  If the repository wasn't cloned:"
echo "    1. Make sure your code is pushed to GitHub"
echo "    2. Or manually place your code in $INSTALL_DIR/"
echo "    3. Then run this installer again"
echo ""